#ifndef _CPU_SYS_PIGEON_H_
#define _CPU_SYS_PIGEON_H_

#include "cpu_subsys_ctrl_pigeon.h"

#define CTRL_BASE_ADDR 0x00600000

#define  RSTCTRL_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_CPURSTCTRL_OFFSET_REG)

#define OTHERRSTCTRL0_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_OTHERRSTCTRL0_OFFSET_REG)

#define OTHERRSTCTRL1_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_OTHERRSTCTRL1_OFFSET_REG)

#define  BUSRSTCTRL_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_BUSRSTCTRL_OFFSET_REG)

#define  RVBADDR0_L (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_RVBARADDR0L_OFFSET_REG)

#define  RVBADDR0_H (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_RVBARADDR0H_OFFSET_REG)

#define  RVBADDR1_L (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_RVBARADDR1L_OFFSET_REG)

#define  RVBADDR1_H (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_RVBARADDR1H_OFFSET_REG)

#define ASTARTMP_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_ASTARTMP_OFFSET_REG)
#define AENDMP_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_AENDMP_OFFSET_REG)
#define CBWBYPASS_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_CBWBYPASS_OFFSET_REG)

#define CRGREGEN0_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_CRGREGEN0_OFFSET_REG)
#define CRGREGEN1_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_CRGREGEN1_OFFSET_REG)
#define CRGREGEN2_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_CRGREGEN2_OFFSET_REG)

#define CLUSTER_CACHE_M0_BYP_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_CLUSTER_CACHE_M0_BYP_OFFSET_REG)
#define CLUSTER_AWCACHE_M0_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_CLUSTER_AWCACHE_M0_VAL_OFFSET_REG)
#define CLUSTER_ARCACHE_M0_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_CLUSTER_ARCACHE_M0_VAL_OFFSET_REG)
#define CLUSTER_CACHE_M1_BYP_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_CLUSTER_CACHE_M1_BYP_OFFSET_REG)
#define CLUSTER_AWCACHE_M1_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_CLUSTER_AWCACHE_M1_VAL_OFFSET_REG)
#define CLUSTER_ARCACHE_M1_ADDR (CTRL_BASE_ADDR + CPU_SUBSYS_CTRL_CLUSTER_ARCACHE_M1_VAL_OFFSET_REG)

#endif
