#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#define FILE_NAME_LEN		256
#define MAX_PHYS_CARD		16
#define MAX_SMLU_INSTANCE_COUNT	64
#define SMLU_AVERAGE_TOTAL	512

struct average_s {
	int average; /* for cnmon show to user */
	int head;
	int total;
	int average_t[SMLU_AVERAGE_TOTAL];
} average_arr[MAX_SMLU_INSTANCE_COUNT] = {{0}};

int stringRemoveDelimiter(char delimiter, const char *string)
{
	int string_start = 0;

	while (string[string_start] == delimiter) {
		string_start++;
	}

	if (string_start >= (int)(strlen(string) - 1)) {
		return 0;
	}

	return string_start;
}

bool getCmdLineArgumentString(const int argc, const char **argv,
		const char *string_ref,
		char **string_retval)
{
	bool bFound = false;
	int i;

	if (argc >= 1) {
		for (i = 1; i < argc; i++) {
			int string_start = stringRemoveDelimiter('-', argv[i]);
			char *string_argv = (char *)(&argv[i][string_start]);
			int length = (int)(strlen(string_ref));

			if (!strncmp(string_argv, string_ref, length)) {
				*string_retval = &string_argv[length + 1];
				bFound = true;
				break;
			}
		}
	}

	if (!bFound) {
		*string_retval = NULL;
	}

	return bFound;
}

void print_help(char *bin_name) {
	printf("Usage:\n");
	printf("%s --card_id=<card_id> --json_path=<json_path> --save_path=<save_path>\n", bin_name);
	printf("\t<card_id>: 0/1/2..., check with cnmon\n");
	printf("\t<json_path>: path of trace.json generated by cambricon_util_drv\n");
	printf("\t<save_path>: directory of .svg file saved in\n");
	printf("%s -h/--help: get current usage info\n", bin_name);
	printf("\n");
}

int main(int argc, char *argv[]) {
	int mlu, inst;
	int target, usage;
	int i, ret = 0;
	FILE *fp_in, *fp_out;
	char line[1024];
	char *card_id_str = NULL;
	int card_id;
	char *input_file = NULL;
	char *output_path = NULL;
	char output_file[FILE_NAME_LEN];
	char middle_file[MAX_SMLU_INSTANCE_COUNT][FILE_NAME_LEN] = {{0}}; /* record and delete them finally*/
	char data[64];
	struct average_s *res;
	int old;
	uint64_t instance_mask = 0; /* bit map of smlu instance */
	int instance_num = 0;
	int layout_x, layout_y; /* used by gnuplot */
	char cmd_buf[512];

	/* args check */
	for (i = 1; i < argc; i++) {
		if(strstr(argv[i], "-h") || strstr(argv[i], "--help")) {
			print_help(argv[0]);
			return 0;
		}
	}
	if (argc <= 3) {
		printf("Error input args\n");
		printf("Usage: %s --help to get usage info\n", argv[0]);
		return -1;
	}

	/* args parse */
	if (getCmdLineArgumentString(argc, (const char **)argv, "card_id", &card_id_str)) {
		card_id = atoi(card_id_str);
		if (card_id >= MAX_PHYS_CARD) {
			printf("Invalid card_id: %d\n", card_id);
			return -1;
		}
	} else {
		printf("card_id not detected\n");
		return -1;
	}

	if (!getCmdLineArgumentString(argc, (const char **)argv, "json_path", &input_file)) {
		printf("json_path not detected\n");
		return -1;
	}

	if (!getCmdLineArgumentString(argc, (const char **)argv, "save_path", &output_path)) {
		printf("save_path not detected\n");
		return -1;
	}

	/* read in json file */
	fp_in = fopen(input_file, "r");
	if (fp_in == NULL) {
	    printf("Failed to open file \"%s\"\n", input_file);
	    return -1;
	}

	while (fgets(line, sizeof(line), fp_in)) {
		/* params parse */
		ret = sscanf(line, "%*[^:]:%*[^:]:\"%*[^-]-%d\", \"%*[^-]-%d", &mlu, &inst);
		if (ret != 2 || mlu != card_id)
			continue;
		sscanf(line, "%*[^:]: \"target=%d,usage=%d", &target, &usage);

		/* set bit map of smlu instance */
		instance_mask |= ((uint64_t)0x1 << inst);

		/* calculate average usage value */
		res = &average_arr[inst];
		old = res->average_t[res->head];
		res->average_t[res->head] = usage;
		res->total = (res->total + res->average_t[res->head]) - old;
		res->head++;
		if (res->head == SMLU_AVERAGE_TOTAL)
			res->head = 0;
		res->average = res->total / SMLU_AVERAGE_TOTAL;

		/* write to file */
		memset(output_file, 0, sizeof(output_file));
		snprintf(output_file, sizeof(output_file),
			"%s/dev%dinst%d.csv", output_path, mlu, inst);
		fp_out = fopen(output_file, "a");
		if (fp_out == NULL) {
			printf("Failed to open file \"%s\"\n", output_file);
			ret = -1;
			goto err_close;
		}
		sprintf(data, "%d %d %d\n", target, usage, res->average);
		fputs(data, fp_out);
		strcpy(middle_file[inst], output_file);
		fclose(fp_out);
	}

	/* calculate instance_num for gnuplot layout */
	i = 0;
	while (instance_mask) {
		instance_num += (instance_mask & (0x1 << i));
		instance_mask = (instance_mask >> 1);
	}
	printf("card_id:%d, instance_num:%d, ploting...\n", card_id, instance_num);

	/* construct gnuplot command */
	layout_x = instance_num > 2 ? 2 : 1;
	layout_y = instance_num > 1 ? 2 : 1;

	snprintf(cmd_buf, sizeof(cmd_buf), "gnuplot -e \"card_id=%d; max_instance_count=%d; \
		layout_x=%d; layout_y=%d; input_path=\'%s\'; output_file=\'%s/dev%d_ipu_util.svg\'; \
		title_name=\'IPU UTIL FOR CARD %d (Time / ms)\'\" ./gnuplot/gen_svg.plt",
		card_id, MAX_SMLU_INSTANCE_COUNT, layout_x, layout_y,  output_path, output_path, card_id, card_id);
	ret = system(cmd_buf);
	if (!ret) {
		printf("plot finished, output file saved at \"%s/dev%d_ipu_util.svg\"\n",
			output_path, card_id);
	} else {
		printf("plot failed, ret:%d\n", ret);
	}

	/* delete middle file */
	for (i = 0; i < MAX_SMLU_INSTANCE_COUNT; i++) {
		if (!strcmp(middle_file[i], ""))
			continue;
		ret = remove(middle_file[i]);
		if (ret) {
			printf("failed to delete mid-file \"%s\"\n", middle_file[i]);
		}
	}

err_close:
	fclose(fp_in);
	return ret;
}
